In [1]:
list_1 = [1, 2, 3]
print(list_1)

[1, 2, 3]


In [2]:
import numpy as np


In [3]:
numpy_1 = np.array(list_1)
print(numpy_1)

[1 2 3]


In [4]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [5]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
range_array_1 = np.arange(5)
print(range_array_1)

[0 1 2 3 4]


In [7]:
range_array_2 = np.arange(5, 11) # remember, upper bounds is not inclusive
print(range_array_2)

[ 5  6  7  8  9 10]


In [8]:
range_array_3 = np.arange(0, 20, 2) # 3rd param is step value (how many to skip)
print(range_array_3)

[ 0  2  4  6  8 10 12 14 16 18]


In [9]:
linspace_array = np.linspace(0, 10, 10) # 3rd param default is 50, specifies how many elements to generate, evenly spaced
# upperbound (param 2) i
print(linspace_array)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [10]:
numpy_1 = np.array(list_1)
print(numpy_1)

[1 2 3]


In [11]:
zeros_array = np.zeros(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [12]:
ones_array = np.ones(10)
print(ones_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
range_array_1 = np.arange(5)
print(range_array_1)

[0 1 2 3 4]


In [14]:
range_array_2 = np.arange(5, 11) # remember, upper bounds is not inclusive
print(range_array_2)

[ 5  6  7  8  9 10]


In [15]:
range_array_3 = np.arange(0, 20, 2) # 3rd param is step value (how many to skip)
print(range_array_3)

[ 0  2  4  6  8 10 12 14 16 18]


In [16]:
linspace_array = np.linspace(0, 10, 10) # 3rd param default is 50, specifies how many elements to generate, evenly spaced
# upperbound (param 2) i
print(linspace_array)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
