# Intro to Matrices in Numpy
* Talk about what matrices are and why they're important
    * A matrix is a multidimensional array
    * Essentially an array of arrays
    * Used in images, geological data, machine learning, and anything graph related
    * Examples
        * An Image of 1 might look like this:
            [[0,0,1,0,0],
             [0,0,1,0,0],
             [0,0,1,0,0],
             [0,0,1,0,0],
             [0,0,1,0,0],]
* Create a custom matrix
* Create a matrix of ones or zeroes

In [1]:
import numpy as np

In [2]:
# How to create a matrix
two_by_two = np.matrix([[1,2],[3,4]])
print(two_by_two)

[[1 2]
 [3 4]]


In [3]:
# No limit other than computation
# Each list should be the same size


In [4]:
two_by_three = np.matrix('1 2; 3 4; 5 6')
print(two_by_three)


[[1 2]
 [3 4]
 [5 6]]


In [6]:
# Above is create matrices by specifying explicitly 
# Below use np.zeros etc
zero_matrix_two_by_three = np.zeros([3, 2]) # np.zeros([<number_of_lists, <number_of_elements])
print(zero_matrix_two_by_three)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [7]:
ones_matrix_two_by_15 = np.zeros([15, 2])
print(ones_matrix_two_by_15)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
