# Numpy Matrix Fetch Functions
* Get elements based on index
* Get Slices
* Get size and shape
* Get max, min, and average

In [1]:
import numpy as np

In [2]:
a_matrix = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
# get full row
print(a_matrix[0])

[[1 2 3]]


In [5]:
# get single element: row, column
print(a_matrix[1,0])

4


In [7]:
# get slices: Get 8, 9
print(a_matrix[2, 1:])

[[8 9]]


In [8]:
# or
print(a_matrix[2, 1:3])

[[8 9]]


In [9]:
# Get size
print(a_matrix.size)
# Get Shape
print(a_matrix.shape)

9
(3, 3)


In [12]:
# Get max
print(np.amax(a_matrix), "Using np.amax()")

# Or
print(a_matrix.max(), "Using <array>.max()")

# Get min
print(np.amin(a_matrix), "Using np.amin()")

# Or
print(a_matrix.min(), "Using <array>.min()")

# Get Average
print(np.average(a_matrix), "Using np.average()")

# Or
print(a_matrix.mean(), "Using <array>.mean()")

9 Using np.amax()
9 Using <array>.max()
1 Using np.amin()
1 Using <array>.min()
5.0 Using np.average()
5.0 Using <array>.mean()


In [13]:
# Above is personal preference, most likely same efficiency 