# Numpy Matrices by Example
* Create a matrix to represent a number
* Change the number from black to white
* Rotate the number

In [1]:
import numpy as np

In [9]:
image_matrix = np.matrix([[0,0,1,0,0],[0,0,1,0,0],[1,1,1,1,1],[0,0,1,0,0],[0,0,1,0,0]])
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [10]:
# Reverse the colors (0 = White, 1 = Black)
rows = image_matrix.shape[0]
columns = image_matrix.shape[1]
for row in range(rows):
    for column in range(columns):
        if image_matrix[row, column] == 0:
            image_matrix[row, column] = 1;
        else:
            image_matrix[row, column] = 0;
print(image_matrix)

[[1 1 0 1 1]
 [1 1 0 1 1]
 [0 0 0 0 0]
 [1 1 0 1 1]
 [1 1 0 1 1]]


In [13]:
# Reset the matrix to not a T
image_matrix = np.matrix([[0,0,1,0,0],[0,0,1,0,0],[0,0,1,0,0],[0,0,1,0,0],[0,0,1,0,0]])
print(image_matrix)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [14]:
# Rotate the image
print(image_matrix.T)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]]
