In [1]:
# Get Elements based on index
# Slice Arrays
# Access ranges
# Get length of arrays
# Get max, min, average of arrays

In [ ]:
import numpy as np

In [7]:
an_array = np.arange(0, 11)
print(an_array)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [9]:
first_element = an_array[0]
print(first_element)
last_element = an_array[10]
print(last_element)

0
10


In [ ]:
first_five = an_array[:5]
print(first_five)

In [ ]:
last_five = an_array[6:]
print(last_five)

In [ ]:
last_five_stride_2 = an_array[6::2]
print(last_five_stride_2)

In [ ]:
last_five_count_down = an_array[10:5:-1]
print(last_five_count_down)

In [ ]:
first_five_reversed = an_array[4::-1]
print(first_five_reversed)

In [ ]:
final_two = an_array[-2:]
print(final_two)

In [ ]:
# get length
print(an_array.size)

In [ ]:
# get min
print(np.amin(an_array))

In [ ]:
# get max
print(np.amax(an_array))

In [ ]:
# get average
print(np.average(an_array))

[0 1 2 3 4]


In [11]:
last_five = an_array[6:]
print(last_five)

[ 6  7  8  9 10]


In [13]:
last_five_stride_2 = an_array[6::2]
print(last_five_stride_2)

[ 6  8 10]


In [17]:
last_five_count_down = an_array[10:5:-1]
print(last_five_count_down)

[10  9  8  7  6]


In [18]:
first_five_reversed = an_array[4::-1]
print(first_five_reversed)

[4 3 2 1 0]


In [19]:
final_two = an_array[-2:]
print(final_two)

[ 9 10]


In [20]:
# get length
print(an_array.size)

11


In [22]:
# get min
print(np.amin(an_array))

0


In [24]:
# get max
print(np.amax(an_array))

10


In [25]:
# get average
print(np.average(an_array))

5.0
