# Numpy Matrix Modifications
* Change individual elements or rows
* Sort Matrices
* Transpose Matrices
* Multiplication and addition
* Matrix multiplication

In [1]:
import numpy as np

In [3]:
a_matrix = np.matrix([[1, 2],[3, 4]])
print(a_matrix)

[[1 2]
 [3 4]]


In [4]:
# Assign individual elements
a_matrix[1,0] = 10 # <array>[<row>, <element>] = <new_value> Should be single thing
print(a_matrix)

[[ 1  2]
 [10  4]]


In [5]:
# Assign full row
a_matrix[1] = [6, 3] # <array>[<row>] = <new value> Should be an array
print(a_matrix)

[[1 2]
 [6 3]]


In [8]:
# Sort functions
# Sorts each row separately, leaves rows in the same order
print(np.sort(a_matrix), "Ascending order")
# Sort in descending order
print(-np.sort(-a_matrix), "Descending order")

[[1 2]
 [3 6]] Ascending order
[[2 1]
 [6 3]] Descending order


In [10]:
# Transposing
print(a_matrix.T)


[[1 6]
 [2 3]]


In [13]:
# Flatten
print(a_matrix.flatten())

[[1 2 6 3]]


In [16]:
# Scalar Addition
print(a_matrix + 1, "Add one to every element (Scalar Addition)")
# Scalar Multiplication
print(a_matrix * 2, "Multiply each element by 2 (Scalar Multiplication)")
# Numpy Add
print(np.add(a_matrix, a_matrix), "Add two matrices (np.add())")
# Numpy Multiply
print(np.matmul(a_matrix, a_matrix), "Multiply two matrices (np.matmul())")

[[2 3]
 [7 4]] Add one to every element (Scalar Addition)
[[ 2  4]
 [12  6]] Multiply each element by 2 (Scalar Multiplication)
[[ 2  4]
 [12  6]] Add two matrices (np.add())
[[13  8]
 [24 21]] Multiply two matrices (np.matmul())
