Learning about Append, insert, delete, scalar and vector, and sorting operations

In [1]:
import numpy as np

In [2]:
an_array = np.arange(0, 6)
print(an_array)

[0 1 2 3 4 5]


In [3]:
an_array[0] = 10
print(an_array)

[10  1  2  3  4  5]


In [4]:
an_array = np.arange(0, 6)
# Append, insert, delete operations
print(np.append(an_array, [6, 7])) # params: array to append to, element(s) to append (can be single element or list of elements)
print(np.insert(an_array, 0, [10, 11])) # params: array to insert into, index to start insert, element(s) to insert (same options as append)
print(np.delete(an_array, 3))

[0 1 2 3 4 5 6 7]
[10 11  0  1  2  3  4  5]
[0 1 2 4 5]


In [5]:
# Scalar and vector operations
print(an_array * 2)
print(an_array + 2)
print(an_array - 2)
print(an_array / 2)
print(an_array % 2)

[ 0  2  4  6  8 10]
[2 3 4 5 6 7]
[-2 -1  0  1  2  3]
[0.  0.5 1.  1.5 2.  2.5]
[0 1 0 1 0 1]


In [6]:
# Sorting operations
# Default sort ascending
another_array = np.array([2, 4, 8, 1, 9, 0])
print(np.sort(another_array))
# Descending Order, kinda hacky but it works lol. Set array negative, sort, negative the result 
print(-np.sort(-another_array))

[0 1 2 4 8 9]
[9 8 4 2 1 0]
