* Start with a random list of grades
* Obtain the max, min, and average
* Sort in ascending and descending order
* Increase all grades by a % and by adding ones

In [1]:
import numpy as np

In [2]:
student_grades = np.array([56, 78, 98, 90, 58, 64, 67, 72, 93, 51])

In [3]:
class_average = np.average(student_grades)
print(class_average)

72.7


In [4]:
highest_grade = np.amax(student_grades)
print(highest_grade)

98


In [5]:
lowest_grade = np.amin(student_grades)
print(lowest_grade)

51


In [7]:
index_of_max = np.argmax(student_grades)
print(index_of_max)
index_of_min = np.argmin(student_grades)
print(index_of_min)

2
9


In [8]:
ascending_sort = np.sort(student_grades)
decending_sort = -np.sort(-student_grades)
print(ascending_sort)
print(decending_sort)

[51 56 58 64 67 72 78 90 93 98]
[98 93 90 78 72 67 64 58 56 51]


In [10]:
increased_grades = student_grades * 1.1
print(increased_grades)

[ 61.6  85.8 107.8  99.   63.8  70.4  73.7  79.2 102.3  56.1]


In [11]:
increase_grands = student_grades + 10
print(increased_grades)

[ 61.6  85.8 107.8  99.   63.8  70.4  73.7  79.2 102.3  56.1]


In [14]:
print(np.add(student_grades, np.ones(10)))

[57. 79. 99. 91. 59. 65. 68. 73. 94. 52.]


In [17]:
print(np.add(student_grades, np.array([1,2,3,4,5,6,7,8,9,10])))

[ 57  80 101  94  63  70  74  80 102  61]
